# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uihw7.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(210, 70, 41, 121))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.count_cheeseburger = QtWidgets.QLineEdit(self.widget)
        self.count_cheeseburger.setAutoFillBackground(False)
        self.count_cheeseburger.setObjectName("count_cheeseburger")
        self.verticalLayout_2.addWidget(self.count_cheeseburger)
        self.count_humburger = QtWidgets.QLineEdit(self.widget)
        self.count_humburger.setObjectName("count_humburger")
        self.verticalLayout_2.addWidget(self.count_humburger)
        self.count_naggets = QtWidgets.QLineEdit(self.widget)
        self.count_naggets.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.count_naggets)
        self.count_cocacola = QtWidgets.QLineEdit(self.widget)
        self.count_cocacola.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.count_cocacola)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(60, 250, 321, 261))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(60, 70, 144, 166))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cheeseburger = QtWidgets.QCheckBox(self.widget1)
        self.cheeseburger.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.cheeseburger)
        self.humburger = QtWidgets.QCheckBox(self.widget1)
        self.humburger.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.humburger)
        self.naggets = QtWidgets.QCheckBox(self.widget1)
        self.naggets.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.naggets)
        self.cocacola = QtWidgets.QCheckBox(self.widget1)
        self.cocacola.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.cocacola)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cheeseburger.setText(_translate("MainWindow", "Чизбургер"))
        self.humburger.setText(_translate("MainWindow", "Гамбургер"))
        self.naggets.setText(_translate("MainWindow", "Наггетсы"))
        self.cocacola.setText(_translate("MainWindow", "Кока кола"))
        self.pushButton.setText(_translate("MainWindow", "Заказать"))
